version: '2'

services:
  api:
    build: ./infrastructure/nginx
    image: skytsar/nginx
    ports:
    - "80:80"
    volumes:
    - ./app/autoq:/usr/share/nginx/html
    depends_on:
    - phpfpm
    command: /bin/bash -c "envsubst '\$${NGINX_SERVER_NAME} \$${NGINX_FASTCGI_READ_TIMEOUT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  phpfpm:
    build: ./infrastructure/php-fpm
    image: skytsar/phpfpm-phalcon
    volumes:
    - ./app/autoq:/var/www/html
    depends_on:
    - mysql
  postgres:
    build: ./infrastructure/postgres
    image: skytsar/postgres
    hostname: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  mysql:
    build: ./infrastructure/mysql
    image: skytsar/mysql
    hostname: mysql
    expose:
     - 3306
    environment:
      - MYSQL_ROOT_PASSWORD
  go:
    build: ./infrastructure/go
    image: skytsar/go
    volumes:
    - ./app/autoqctl/src/autoqctl:/go/src/autoqctl
    working_dir: /go/src/autoqctl
  basephp:
    build: ./infrastructure/php-cli
    image: skytsar/autoq-basephp
    volumes:
    - ./app/autoq:/usr/src/autoq
    working_dir: /usr/src/autoq
  utils:
    extends:
      service: basephp
    depends_on:
    - mysql
    hostname: utils
  scheduler:
    extends:
      service: basephp
    depends_on:
    - mysql
    command: [php, cli.php, Scheduler]





