version: '2'

services:
  api:
    environment:
    - NGINX_SERVER_NAME=autoq.localdev
    - NGINX_FASTCGI_READ_TIMEOUT=600s
  phpfpm:
    environment:
    - AUTOQ_AUTH
    volumes:
    - ./infrastructure/php-fpm/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  postgres:
    build: ./infrastructure/postgres
    image: skytsar/postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
    - POSTGRES_USER=autoq
    - POSTGRES_PASSWORD=dev
  utils:
    volumes:
    - ./infrastructure/php-cli/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
    - COMPOSER_DISABLE_XDEBUG_WARN=1
    - COMPOSER_ALLOW_SUPERUSER=1
  scheduler:
    volumes:
    - ./infrastructure/php-cli/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  runner:
    volumes:
    - ./infrastructure/php-cli/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  sender:
    volumes:
    - ./infrastructure/php-cli/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  mysql:
    ports:
      - 3306:3306
    volumes:
    - ./infrastructure/mysql/data/base.sql:/docker-entrypoint-initdb.d/base.sql
    - ./infrastructure/mysql/data/dev_user.sql:/docker-entrypoint-initdb.d/dev_user.sql
    environment:
    - MYSQL_ROOT_PASSWORD=dev
  postfix:
    hostname: mail.autoq.localdev
    env_file: ./app/autoq/postfix.env
    build: ./infrastructure/postfix-relay
    image: skytsar/postfix
    expose:
    - 25
