version: '2'

services:
  api:
    environment:
    - NGINX_SERVER_NAME=autoq.localdev
    - NGINX_FASTCGI_READ_TIMEOUT=600s
  phpfpm:
    volumes:
    - ./infrastructure/php-fpm/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  utils:
    volumes:
    - ./infrastructure/php-cli/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
    - PHP_IDE_CONFIG="serverName=docker"
    - XDEBUG_CONFIG="remote_host=192.168.99.1;xdebug.idekey=PHPSTORM"
  scheduler:
    environment:
    - PHP_IDE_CONFIG="serverName=docker"
    - XDEBUG_CONFIG="remote_host=192.168.99.1;xdebug.idekey=PHPSTORM"
    volumes:
    - ./infrastructure/php-cli/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  runner:
    volumes:
    - ./infrastructure/php-cli/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
    - PHP_IDE_CONFIG="serverName=docker"
    - XDEBUG_CONFIG="remote_host=192.168.99.1;xdebug.idekey=PHPSTORM"
  sender:
    volumes:
    - ./infrastructure/php-cli/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
    - PHP_IDE_CONFIG="serverName=docker"
    - XDEBUG_CONFIG="remote_host=192.168.99.1;xdebug.idekey=PHPSTORM"
  postgres:
    environment:
    - POSTGRES_USER=autoq
    - POSTGRES_PASSWORD=dev
    ports:
      - 5432:5432
  mysql:
    ports:
      - 3306:3306
    volumes:
    - ./infrastructure/mysql/data/base.sql:/docker-entrypoint-initdb.d/base.sql
    - ./infrastructure/mysql/data/dev_user.sql:/docker-entrypoint-initdb.d/dev_user.sql
    environment:
    - MYSQL_ROOT_PASSWORD=dev
