version: '2'

services:
  api:
    environment:
    - NGINX_SERVER_NAME=autoq.localdev
    - NGINX_FASTCGI_READ_TIMEOUT=600s
  phpfpm:
    volumes:
    - ./infrastructure/php-fpm/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  postgres:
    ports:
      - 5432:5432
  mysql:
    ports:
      - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=dev
