version: '2'

services:
  api:
    image: skytsar/nginx
    ports:
    - "80:80"
    volumes_from:
    - app
    environment:
    - NGINX_SERVER_NAME=autoq.boydstratton.com
    - NGINX_FASTCGI_READ_TIMEOUT=60s
#    command: /bin/bash -c "sleep 1000"
    command: /bin/bash -c "envsubst '\$${NGINX_SERVER_NAME} \$${NGINX_FASTCGI_READ_TIMEOUT}' < /app/infrastructure/nginx/config/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  phpfpm:
    image: skytsar/phpfpm-phalcon
    volumes:
    - app:/var/www/html
  app:
    image: skytsar/autoq_app
    mem_limit: 128000000



